name: Continuous release

on:
  push:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/compile.yml
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: cc-rpc-linux-amd64
          path: bin/cc-rpc-linux-amd64
      - uses: actions/download-artifact@v3
        with:
          name: cc-rpc-macos-amd64
          path: bin/cc-rpc-macos-amd64
      - uses: actions/download-artifact@v3
        with:
          name: cc-rpc-macos-arm64
          path: bin/cc-rpc-macos-arm64
      - uses: actions/download-artifact@v3
        with:
          name: cc-rpc-win-amd64.exe
          path: bin/cc-rpc-win-amd64.exe
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: bin    
      - name: Upload to continuous release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          ls -lh bin/*
          wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
          bash upload.sh bin/*